$("#q1a1").click(function(){
$("#Q1").fadeOut();
$("#Q2").fadeIn();
});
$("#q1a2").click(function(){
$("#Q1").fadeOut();
$("#Q2").fadeIn();
});
$("#q1a3").click(function(){
$("#Q1").fadeOut();
$("#Q3").fadeIn();
});
$("#q1a4").click(function(){
$("#Q1").fadeOut();
$("#Q3").fadeIn();
});

$("#q2a1").click(function(){
$("#Q2").fadeOut();
$("#Q3").fadeIn();
});
$("#q2a2").click(function(){
$("#Q2").fadeOut();
$("#Q4").fadeIn();
});
$("#q3a1").click(function(){
$("#Q3").fadeOut();
$("#Q5").fadeIn();
});
$("#q3a2").click(function(){
$("#Q3").fadeOut();
$("#FA5").fadeIn();
});
$("#q4a1").click(function(){
$("#Q4").fadeOut();
$("#Q5").fadeIn();
});
$("#q4a2").click(function(){
$("#Q4").fadeOut();
$("#FA5").fadeIn();
});
$("#q5a1").click(function(){
$("#Q5").fadeOut();
$("#FA1").fadeIn();
});
$("#q5a2").click(function(){
$("#Q5").fadeOut();
$("#FA2").fadeIn();
});
$("#q5a3").click(function(){
$("#Q5").fadeOut();
$("#FA3").fadeIn();
});
$("#q5a4").click(function(){
$("#Q5").fadeOut();
$("#FA4").fadeIn();
});

